name: lesagitacteurs
recipe: lamp
config:
    php: '8.1'
    composer_version: '2'
    node: '16'
    via: 'apache'
    webroot: public
    database: mysql:5.7.39
    forward_composer_auth: false
    xdebug: false
    config:
        database: .lando/database.cnf
        php: .lando/php.ini

excludes:
    - var/cache
    - var/log
    - var/sessions

services:
    node:
        type: node:16
        port: false

    mailhog:
        type: mailhog
        hogfrom:
            - appserver

    phpmyadmin:
        type: phpmyadmin

tooling:
    console:
        service: appserver
    node:
        service: node
    yarn:
        service: node
    npm:
        service: node
    npx:
        service: node
    install-deps:
        cmd:
            -   appserver: composer install
            -   node: npm install
    reset-site:
        cmd:
            #-   appserver: composer install
            #-   node: npm install
            -   appserver: composer run-script reset-site
       